version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 2000
      runas: ubuntu

  AfterInstall:
    - location: scripts/docker-start.sh
      timeout: 2000
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 2000
      runas: ubuntu