jwt:
  secret: ${JWT_SECRET:${jwt.secret}}
  access-token-expire-time-seconds: ${JWT_ACCESS_TOKEN_EXPIRE_TIME_SECONDS:${jwt.access-token-expire-time-seconds}}
  refresh-token-expire-time-seconds: ${JWT_REFRESH_TOKEN_EXPIRE_TIME_SECONDS:${jwt.refresh-token-expire-time-seconds}}


logging:
  level:
    org:
      springframework: debug

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/log4u}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:devcos4-team08}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_DEV_CLIENT_ID:${naver.dev.client-id}} # 로컬 기본값
            client-secret: ${NAVER_DEV_CLIENT_SECRET:${naver.dev.client-secret}}
            redirect-uri: ${NAVER_DEV_REDIRECT_URI:${naver.dev.redirect-uri}}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname

          google:
            client-name: google
            client-id: ${GOOGLE_DEV_CLIENT_ID:${google.dev.client-id}}
            client-secret: ${GOOGLE_DEV_CLIENT_SECRET:${google.dev.client-secret}}
            redirect-uri: ${GOOGLE_DEV_REDIRECT_URI:${google.dev.redirect-uri}}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          kakao:
            client-id: ${KAKAO_DEV_CLIENT_ID:${kakao.dev.client-id}}
            client-secret: ${KAKAO_DEV_CLIENT_SECRET:${kakao.dev.client-secret}}
            redirect-uri: ${KAKAO_DEV_REDIRECT_URI:${kakao.dev.redirect-uri}}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id