logging:
  level:
    org:
      springframework: debug

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3307/log4u
    username: dev
    password: devcos4-team08
    driver-class-name: com.mysql.cj.jdbc.Driver
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}  # S3 버킷 이름을 GitHub Secrets에서 참조
    region: ${AWS_REGION:ap-northeast-2}  # 기본값 서울 리전(ap-northeast-2)

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${naver.dev.client-id}
            client-secret: ${naver.dev.client-secret}
            redirect-uri: ${naver.dev.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname

          google:
            client-name: google
            client-id: ${google.dev.client-id}
            client-secret: ${google.dev.client-secret}
            redirect-uri: ${google.dev.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          kakao:
            client-id: ${kakao.dev.client-id}
            client-secret: ${kakao.dev.client-secret}
            redirect-uri: ${kakao.dev.redirect-uri}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id