spring:
  datasource:
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  second-datasource:
    jdbc-url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  aws:
    region: ${AWS_REGION}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}

logging:
  level:
    org:
      springframework: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time-seconds: ${JWT_ACCESS_TOKEN_EXPIRE_TIME_SECONDS}
  refresh-token-expire-time-seconds: ${JWT_REFRESH_TOKEN_EXPIRE_TIME_SECONDS}
