spring:
  profiles:
    group:
      prod: "prod, prod-secret"
      dev: "dev, dev-secret"
    # 프로필 변경 시 사용
    active: dev
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}  # S3 버킷 이름을 GitHub Secrets에서 참조
    region: ${AWS_REGION:ap-northeast-2}  # 기본값 서울 리전(ap-northeast-2)