logging:
  level:
    org:
      springframework: debug

spring:
  profiles:
    include: secret

  datasource:
    url: ${aws-mysql.url}
    username: ${aws-mysql.username}
    password: ${aws-mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create


  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            redirect-uri: ${naver.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - nickname

          google:
            client-name: google
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            redirect-uri: ${google.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}  # S3 버킷 이름을 GitHub Secrets에서 참조
    region: ${AWS_REGION:ap-northeast-2}  # 기본값 서울 리전(ap-northeast-2)